name: Publish to GitHub and Docker

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for creating a release

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: NekoTraceWebVersion
        with:
          proj-path: ./NekoTrace.Web/NekoTrace.Web.csproj

      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir publish
          RELEASE_FILE_PREFIX="NekoTrace-${{ steps.NekoTraceWebVersion.outputs.version }}-"
          for publish_name in Portable Linux64SelfContained Win64 Win64SelfContained;
          do
            dotnet publish ./NekoTrace.Web/NekoTrace.Web.csproj -p:PublishProfile=$publish_name
            cd ./NekoTrace.Web/bin/Release/net9.0/publish/$publish_name
            zip_name=${RELEASE_FILE_PREFIX}${publish_name}.zip
            zip -r $zip_name ./*
            mv $zip_name ../../../../../../publish/$zip_name
            cd ../../../../../..
          done
          gh release create --generate-notes --fail-on-no-commits v${{ steps.NekoTraceWebVersion.outputs.version }} ./publish/*

      - uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Retag and push docker image
        run: |
          docker pull colinbradley/nekotrace:${{ github.sha }}
          docker tag colinbradley/nekotrace:${{ github.sha }} colinbradley/nekotrace:latest
          docker tag colinbradley/nekotrace:${{ github.sha }} colinbradley/nekotrace:v${{ steps.NekoTraceWebVersion.outputs.version }}
          docker push colinbradley/nekotrace:latest
          docker push colinbradley/nekotrace:v${{ steps.NekoTraceWebVersion.outputs.version }}
